import type { SpellDef } from './combatTypes.js';

export const SPELLS: Record<string, SpellDef> = {
  burning_hands: {
    id: 'burning_hands',
    name: 'Burning Hands',
    damage: 12,
    castTime: 12,
    range: 1,
    aoeRadius: 0,
    manaCost: 5,
    animType: 'fire_burst',
    animDurationMs: 680,
    particleCount: 16,
  },
  magic_missile: {
    id: 'magic_missile',
    name: 'Magic Missile',
    damage: 10,
    castTime: 9,
    range: 999,
    aoeRadius: 0,
    manaCost: 8,
    targetType: 'unit',
    animType: 'arcane_bolt',
    animDurationMs: 520,
    particleCount: 9,
  },
  heal: {
    id: 'heal',
    name: 'Heal',
    damage: -15,  // negative = healing
    castTime: 15,
    range: 2,
    aoeRadius: 0,
    manaCost: 10,
    targetType: 'unit',
    animType: 'heal_pulse',
    animDurationMs: 780,
    particleCount: 9,
  },
  fireball: {
    id: 'fireball',
    name: 'Fireball',
    damage: 20,
    castTime: 30,
    range: 8,
    aoeRadius: 3,
    manaCost: 25,
    animType: 'fire_projectile',
    animDurationMs: 950,
    particleCount: 9,
  },
  ice_storm: {
    id: 'ice_storm',
    name: 'Ice Storm',
    damage: 14,
    castTime: 24,
    range: 6,
    aoeRadius: 2,
    manaCost: 18,
    animType: 'frost_storm',
    animDurationMs: 1000,
    particleCount: 22,
  },
};
